"""
Player Hub seed data — 80 players across NFL / MLB / NBA.
Tuned for Whatnot streaming resale: raw card primary, $10-200 buy range.

whatnot_tier:
  1 = INSTANT SELLERS (sell same stream)
  2 = FAST MOVERS (sell within 2 streams)
  3 = STEADY MOVERS (sell within 1 week)
"""

PLAYER_HUB_SEED_VERSION = 4

HUB_CATEGORY_DEFS = [
    {"id": "nfl_qb", "label": "NFL Quarterbacks", "description": "All QB targets."},
    {"id": "nfl_skill", "label": "NFL Skill Positions", "description": "WR/RB/TE/CB targets."},
    {"id": "mlb_star", "label": "MLB Stars", "description": "MLB targets."},
    {"id": "nba_star", "label": "NBA Stars", "description": "NBA targets."},
    {"id": "rookie_2022", "label": "2022 Rookies", "description": "2022 draft class."},
    {"id": "rookie_2023", "label": "2023 Rookies", "description": "2023 draft class."},
    {"id": "rookie_2024", "label": "2024 Rookies", "description": "2024 draft class."},
    {"id": "rookie_2025", "label": "2025 Rookies", "description": "2025 draft class."},
    {"id": "nfl_wr",  "label": "NFL Wide Receivers",  "description": "WR targets."},
    {"id": "nfl_rb",  "label": "NFL Running Backs",   "description": "RB targets."},
    {"id": "nfl_te",  "label": "NFL Tight Ends",      "description": "TE targets."},
    {"id": "whatnot_t1", "label": "Whatnot Tier 1 - Instant", "description": "Sells same stream."},
    {"id": "whatnot_t2", "label": "Whatnot Tier 2 - Fast", "description": "Sells within 2 streams."},
    {"id": "whatnot_t3", "label": "Whatnot Tier 3 - Steady", "description": "Sells within 1 week."},
]

# ─────────────────────────────────────────────────────────────────────────────
# NFL — 52 players (21 QBs + 31 Skill/RB/TE incl. 2025 rookies)
# ─────────────────────────────────────────────────────────────────────────────
_NFL_PLAYERS = [
    # QBs
    {
        "player_id": "patrick_mahomes",
        "player_name": "Patrick Mahomes",
        "sport": "Football",
        "position": "QB",
        "team": "KC",
        "rookie_year": 2017,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1"],
        "match_tokens": ["patrick mahomes", "mahomes"],
        "search_query_hint": "Patrick Mahomes",
    },
    {
        "player_id": "josh_allen",
        "player_name": "Josh Allen",
        "sport": "Football",
        "position": "QB",
        "team": "BUF",
        "rookie_year": 2018,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1"],
        "match_tokens": ["josh allen"],
        "search_query_hint": "Josh Allen",
    },
    {
        "player_id": "lamar_jackson",
        "player_name": "Lamar Jackson",
        "sport": "Football",
        "position": "QB",
        "team": "BAL",
        "rookie_year": 2018,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1"],
        "match_tokens": ["lamar jackson"],
        "search_query_hint": "Lamar Jackson",
    },
    {
        "player_id": "jalen_hurts",
        "player_name": "Jalen Hurts",
        "sport": "Football",
        "position": "QB",
        "team": "PHI",
        "rookie_year": 2020,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2"],
        "match_tokens": ["jalen hurts"],
        "search_query_hint": "Jalen Hurts",
    },
    {
        "player_id": "joe_burrow",
        "player_name": "Joe Burrow",
        "sport": "Football",
        "position": "QB",
        "team": "CIN",
        "rookie_year": 2020,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2"],
        "match_tokens": ["joe burrow", "burrow"],
        "search_query_hint": "Joe Burrow",
    },
    {
        "player_id": "cj_stroud",
        "player_name": "C.J. Stroud",
        "sport": "Football",
        "position": "QB",
        "team": "HOU",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2", "rookie_2023"],
        "match_tokens": ["c.j. stroud", "cj stroud", "stroud"],
        "search_query_hint": "CJ Stroud",
    },
    {
        "player_id": "bryce_young",
        "player_name": "Bryce Young",
        "sport": "Football",
        "position": "QB",
        "team": "CAR",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2", "rookie_2023"],
        "match_tokens": ["bryce young"],
        "search_query_hint": "Bryce Young",
    },
    {
        "player_id": "caleb_williams",
        "player_name": "Caleb Williams",
        "sport": "Football",
        "position": "QB",
        "team": "CHI",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1", "rookie_2024"],
        "match_tokens": ["caleb williams"],
        "search_query_hint": "Caleb Williams rookie",
    },
    {
        "player_id": "drake_maye",
        "player_name": "Drake Maye",
        "sport": "Football",
        "position": "QB",
        "team": "NE",
        "rookie_year": 2024,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2", "rookie_2024"],
        "match_tokens": ["drake maye"],
        "search_query_hint": "Drake Maye rookie",
    },
    {
        "player_id": "jayden_daniels",
        "player_name": "Jayden Daniels",
        "sport": "Football",
        "position": "QB",
        "team": "WSH",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1", "rookie_2024"],
        "match_tokens": ["jayden daniels"],
        "search_query_hint": "Jayden Daniels rookie",
    },
    {
        "player_id": "kyler_murray",
        "player_name": "Kyler Murray",
        "sport": "Football",
        "position": "QB",
        "team": "ARI",
        "rookie_year": 2019,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3"],
        "match_tokens": ["kyler murray"],
        "search_query_hint": "Kyler Murray",
    },
    {
        "player_id": "michael_penix",
        "player_name": "Michael Penix Jr.",
        "sport": "Football",
        "position": "QB",
        "team": "ATL",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["michael penix", "penix jr"],
        "search_query_hint": "Michael Penix Jr rookie",
    },
    {
        "player_id": "dak_prescott",
        "player_name": "Dak Prescott",
        "sport": "Football",
        "position": "QB",
        "team": "DAL",
        "rookie_year": 2016,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3"],
        "match_tokens": ["dak prescott", "prescott"],
        "search_query_hint": "Dak Prescott",
    },
    {
        "player_id": "justin_herbert",
        "player_name": "Justin Herbert",
        "sport": "Football",
        "position": "QB",
        "team": "LAC",
        "rookie_year": 2020,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3"],
        "match_tokens": ["justin herbert"],
        "search_query_hint": "Justin Herbert",
    },
    {
        "player_id": "trevor_lawrence",
        "player_name": "Trevor Lawrence",
        "sport": "Football",
        "position": "QB",
        "team": "JAX",
        "rookie_year": 2021,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3"],
        "match_tokens": ["trevor lawrence"],
        "search_query_hint": "Trevor Lawrence",
    },
    # Skill Positions
    {
        "player_id": "justin_jefferson",
        "player_name": "Justin Jefferson",
        "sport": "Football",
        "position": "WR",
        "team": "MIN",
        "rookie_year": 2020,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "whatnot_t1"],
        "match_tokens": ["justin jefferson"],
        "search_query_hint": "Justin Jefferson",
    },
    {
        "player_id": "ceedee_lamb",
        "player_name": "CeeDee Lamb",
        "sport": "Football",
        "position": "WR",
        "team": "DAL",
        "rookie_year": 2020,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "whatnot_t1"],
        "match_tokens": ["ceedee lamb", "cee dee lamb"],
        "search_query_hint": "CeeDee Lamb",
    },
    {
        "player_id": "davante_adams",
        "player_name": "Davante Adams",
        "sport": "Football",
        "position": "WR",
        "team": "LV",
        "rookie_year": 2014,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3"],
        "match_tokens": ["davante adams"],
        "search_query_hint": "Davante Adams",
    },
    {
        "player_id": "jamarrchase",
        "player_name": "Ja'Marr Chase",
        "sport": "Football",
        "position": "WR",
        "team": "CIN",
        "rookie_year": 2021,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "whatnot_t2"],
        "match_tokens": ["ja'marr chase", "jamarr chase"],
        "search_query_hint": "Jamarr Chase",
    },
    {
        "player_id": "puka_nacua",
        "player_name": "Puka Nacua",
        "sport": "Football",
        "position": "WR",
        "team": "LAR",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["puka nacua"],
        "search_query_hint": "Puka Nacua",
    },
    {
        "player_id": "malik_nabers",
        "player_name": "Malik Nabers",
        "sport": "Football",
        "position": "WR",
        "team": "NYG",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["malik nabers"],
        "search_query_hint": "Malik Nabers rookie",
    },
    {
        "player_id": "bijan_robinson",
        "player_name": "Bijan Robinson",
        "sport": "Football",
        "position": "RB",
        "team": "ATL",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["bijan robinson"],
        "search_query_hint": "Bijan Robinson",
    },
    {
        "player_id": "breece_hall",
        "player_name": "Breece Hall",
        "sport": "Football",
        "position": "RB",
        "team": "NYJ",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["breece hall"],
        "search_query_hint": "Breece Hall",
    },
    {
        "player_id": "sauce_gardner",
        "player_name": "Sauce Gardner",
        "sport": "Football",
        "position": "CB",
        "team": "NYJ",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["sauce gardner", "ahmad gardner"],
        "search_query_hint": "Sauce Gardner",
    },
    {
        "player_id": "drake_london",
        "player_name": "Drake London",
        "sport": "Football",
        "position": "WR",
        "team": "ATL",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["drake london"],
        "search_query_hint": "Drake London",
    },
    {
        "player_id": "garrett_wilson",
        "player_name": "Garrett Wilson",
        "sport": "Football",
        "position": "WR",
        "team": "NYJ",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["garrett wilson"],
        "search_query_hint": "Garrett Wilson",
    },
    {
        "player_id": "chris_olave",
        "player_name": "Chris Olave",
        "sport": "Football",
        "position": "WR",
        "team": "NO",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["chris olave"],
        "search_query_hint": "Chris Olave",
    },
    {
        "player_id": "rashee_rice",
        "player_name": "Rashee Rice",
        "sport": "Football",
        "position": "WR",
        "team": "KC",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["rashee rice"],
        "search_query_hint": "Rashee Rice",
    },
    {
        "player_id": "travis_kelce",
        "player_name": "Travis Kelce",
        "sport": "Football",
        "position": "TE",
        "team": "KC",
        "rookie_year": 2013,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3"],
        "match_tokens": ["travis kelce"],
        "search_query_hint": "Travis Kelce",
    },
    {
        "player_id": "sam_laporta",
        "player_name": "Sam LaPorta",
        "sport": "Football",
        "position": "TE",
        "team": "DET",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["sam laporta"],
        "search_query_hint": "Sam LaPorta",
    },
    # ── Additional QBs ───────────────────────────────────────────────────────
    {
        "player_id": "jordan_love",
        "player_name": "Jordan Love",
        "sport": "Football",
        "position": "QB",
        "team": "GB",
        "rookie_year": 2020,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2"],
        "match_tokens": ["jordan love"],
        "search_query_hint": "Jordan Love",
    },
    {
        "player_id": "anthony_richardson",
        "player_name": "Anthony Richardson",
        "sport": "Football",
        "position": "QB",
        "team": "IND",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2", "rookie_2023"],
        "match_tokens": ["anthony richardson"],
        "search_query_hint": "Anthony Richardson rookie",
    },
    {
        "player_id": "tua_tagovailoa",
        "player_name": "Tua Tagovailoa",
        "sport": "Football",
        "position": "QB",
        "team": "MIA",
        "rookie_year": 2020,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3"],
        "match_tokens": ["tua tagovailoa", "tua"],
        "search_query_hint": "Tua Tagovailoa",
    },
    {
        "player_id": "bo_nix",
        "player_name": "Bo Nix",
        "sport": "Football",
        "position": "QB",
        "team": "DEN",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nfl_qb", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["bo nix"],
        "search_query_hint": "Bo Nix rookie",
    },
    {
        "player_id": "shedeur_sanders",
        "player_name": "Shedeur Sanders",
        "sport": "Football",
        "position": "QB",
        "team": "DAL",
        "rookie_year": 2025,
        "whatnot_tier": 1,
        "category_tags": ["nfl_qb", "whatnot_t1", "rookie_2025"],
        "match_tokens": ["shedeur sanders", "shedeur"],
        "search_query_hint": "Shedeur Sanders rookie",
    },
    {
        "player_id": "cam_ward",
        "player_name": "Cam Ward",
        "sport": "Football",
        "position": "QB",
        "team": "TEN",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["nfl_qb", "whatnot_t2", "rookie_2025"],
        "match_tokens": ["cam ward"],
        "search_query_hint": "Cam Ward rookie",
    },
    # ── WRs ──────────────────────────────────────────────────────────────────
    {
        "player_id": "tyreek_hill",
        "player_name": "Tyreek Hill",
        "sport": "Football",
        "position": "WR",
        "team": "MIA",
        "rookie_year": 2016,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t1"],
        "match_tokens": ["tyreek hill", "cheetah"],
        "search_query_hint": "Tyreek Hill",
    },
    {
        "player_id": "amon_ra_st_brown",
        "player_name": "Amon-Ra St. Brown",
        "sport": "Football",
        "position": "WR",
        "team": "DET",
        "rookie_year": 2021,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t2"],
        "match_tokens": ["amon-ra st. brown", "amon ra st brown", "amon-ra"],
        "search_query_hint": "Amon-Ra St Brown",
    },
    {
        "player_id": "marvin_harrison_jr",
        "player_name": "Marvin Harrison Jr.",
        "sport": "Football",
        "position": "WR",
        "team": "ARI",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t1", "rookie_2024"],
        "match_tokens": ["marvin harrison jr", "marvin harrison"],
        "search_query_hint": "Marvin Harrison Jr rookie",
    },
    {
        "player_id": "brian_thomas_jr",
        "player_name": "Brian Thomas Jr.",
        "sport": "Football",
        "position": "WR",
        "team": "JAX",
        "rookie_year": 2024,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t2", "rookie_2024"],
        "match_tokens": ["brian thomas jr", "brian thomas"],
        "search_query_hint": "Brian Thomas Jr rookie",
    },
    {
        "player_id": "tee_higgins",
        "player_name": "Tee Higgins",
        "sport": "Football",
        "position": "WR",
        "team": "CIN",
        "rookie_year": 2020,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t3"],
        "match_tokens": ["tee higgins"],
        "search_query_hint": "Tee Higgins",
    },
    {
        "player_id": "devonta_smith",
        "player_name": "DeVonta Smith",
        "sport": "Football",
        "position": "WR",
        "team": "PHI",
        "rookie_year": 2021,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t3"],
        "match_tokens": ["devonta smith", "de'vonta smith"],
        "search_query_hint": "DeVonta Smith",
    },
    {
        "player_id": "rome_odunze",
        "player_name": "Rome Odunze",
        "sport": "Football",
        "position": "WR",
        "team": "CHI",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["rome odunze"],
        "search_query_hint": "Rome Odunze rookie",
    },
    {
        "player_id": "xavier_worthy",
        "player_name": "Xavier Worthy",
        "sport": "Football",
        "position": "WR",
        "team": "KC",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["xavier worthy"],
        "search_query_hint": "Xavier Worthy rookie",
    },
    {
        "player_id": "travis_hunter",
        "player_name": "Travis Hunter",
        "sport": "Football",
        "position": "WR",
        "team": "JAX",
        "rookie_year": 2025,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "nfl_wr", "whatnot_t1", "rookie_2025"],
        "match_tokens": ["travis hunter"],
        "search_query_hint": "Travis Hunter rookie",
    },
    # ── RBs ──────────────────────────────────────────────────────────────────
    {
        "player_id": "christian_mccaffrey",
        "player_name": "Christian McCaffrey",
        "sport": "Football",
        "position": "RB",
        "team": "SF",
        "rookie_year": 2017,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "nfl_rb", "whatnot_t1"],
        "match_tokens": ["christian mccaffrey", "mccaffrey", "cmc"],
        "search_query_hint": "Christian McCaffrey",
    },
    {
        "player_id": "saquon_barkley",
        "player_name": "Saquon Barkley",
        "sport": "Football",
        "position": "RB",
        "team": "PHI",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "nfl_rb", "whatnot_t2"],
        "match_tokens": ["saquon barkley", "barkley"],
        "search_query_hint": "Saquon Barkley",
    },
    {
        "player_id": "devon_achane",
        "player_name": "De'Von Achane",
        "sport": "Football",
        "position": "RB",
        "team": "MIA",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "nfl_rb", "whatnot_t2", "rookie_2023"],
        "match_tokens": ["de'von achane", "devon achane", "achane"],
        "search_query_hint": "Devon Achane",
    },
    {
        "player_id": "ashton_jeanty",
        "player_name": "Ashton Jeanty",
        "sport": "Football",
        "position": "RB",
        "team": "LV",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["nfl_skill", "nfl_rb", "whatnot_t2", "rookie_2025"],
        "match_tokens": ["ashton jeanty", "jeanty"],
        "search_query_hint": "Ashton Jeanty rookie",
    },
    # ── TEs ──────────────────────────────────────────────────────────────────
    {
        "player_id": "brock_bowers",
        "player_name": "Brock Bowers",
        "sport": "Football",
        "position": "TE",
        "team": "LV",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nfl_skill", "nfl_te", "whatnot_t1", "rookie_2024"],
        "match_tokens": ["brock bowers", "bowers"],
        "search_query_hint": "Brock Bowers rookie",
    },
    {
        "player_id": "trey_mcbride",
        "player_name": "Trey McBride",
        "sport": "Football",
        "position": "TE",
        "team": "ARI",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nfl_skill", "nfl_te", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["trey mcbride"],
        "search_query_hint": "Trey McBride",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# MLB — 25 players
# ─────────────────────────────────────────────────────────────────────────────
_MLB_PLAYERS = [
    {
        "player_id": "shohei_ohtani",
        "player_name": "Shohei Ohtani",
        "sport": "Baseball",
        "position": "DH/P",
        "team": "LAD",
        "rookie_year": 2018,
        "whatnot_tier": 1,
        "category_tags": ["mlb_star", "whatnot_t1"],
        "match_tokens": ["shohei ohtani", "ohtani"],
        "search_query_hint": "Shohei Ohtani",
    },
    {
        "player_id": "paul_skenes",
        "player_name": "Paul Skenes",
        "sport": "Baseball",
        "position": "P",
        "team": "PIT",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["mlb_star", "whatnot_t1", "rookie_2024"],
        "match_tokens": ["paul skenes", "skenes"],
        "search_query_hint": "Paul Skenes rookie",
    },
    {
        "player_id": "juan_soto",
        "player_name": "Juan Soto",
        "sport": "Baseball",
        "position": "OF",
        "team": "NYM",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["mlb_star", "whatnot_t2"],
        "match_tokens": ["juan soto"],
        "search_query_hint": "Juan Soto",
    },
    {
        "player_id": "gunnar_henderson",
        "player_name": "Gunnar Henderson",
        "sport": "Baseball",
        "position": "SS",
        "team": "BAL",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["mlb_star", "whatnot_t2", "rookie_2023"],
        "match_tokens": ["gunnar henderson"],
        "search_query_hint": "Gunnar Henderson",
    },
    {
        "player_id": "jackson_holliday",
        "player_name": "Jackson Holliday",
        "sport": "Baseball",
        "position": "SS",
        "team": "BAL",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["jackson holliday"],
        "search_query_hint": "Jackson Holliday rookie",
    },
    {
        "player_id": "elly_de_la_cruz",
        "player_name": "Elly De La Cruz",
        "sport": "Baseball",
        "position": "SS",
        "team": "CIN",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["elly de la cruz", "elly dela cruz"],
        "search_query_hint": "Elly De La Cruz",
    },
    {
        "player_id": "corbin_carroll",
        "player_name": "Corbin Carroll",
        "sport": "Baseball",
        "position": "OF",
        "team": "ARI",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["corbin carroll"],
        "search_query_hint": "Corbin Carroll",
    },
    {
        "player_id": "bobby_witt_jr",
        "player_name": "Bobby Witt Jr.",
        "sport": "Baseball",
        "position": "SS",
        "team": "KC",
        "rookie_year": 2022,
        "whatnot_tier": 2,
        "category_tags": ["mlb_star", "whatnot_t2", "rookie_2022"],
        "match_tokens": ["bobby witt", "bobby witt jr"],
        "search_query_hint": "Bobby Witt Jr",
    },
    {
        "player_id": "julio_rodriguez",
        "player_name": "Julio Rodriguez",
        "sport": "Baseball",
        "position": "OF",
        "team": "SEA",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["julio rodriguez"],
        "search_query_hint": "Julio Rodriguez",
    },
    {
        "player_id": "francisco_lindor",
        "player_name": "Francisco Lindor",
        "sport": "Baseball",
        "position": "SS",
        "team": "NYM",
        "rookie_year": 2015,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3"],
        "match_tokens": ["francisco lindor", "lindor"],
        "search_query_hint": "Francisco Lindor",
    },
    {
        "player_id": "ronald_acuna_jr",
        "player_name": "Ronald Acuna Jr.",
        "sport": "Baseball",
        "position": "OF",
        "team": "ATL",
        "rookie_year": 2018,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3"],
        "match_tokens": ["ronald acuna", "acuna jr"],
        "search_query_hint": "Ronald Acuna Jr",
    },
    {
        "player_id": "freddie_freeman",
        "player_name": "Freddie Freeman",
        "sport": "Baseball",
        "position": "1B",
        "team": "LAD",
        "rookie_year": 2010,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3"],
        "match_tokens": ["freddie freeman"],
        "search_query_hint": "Freddie Freeman",
    },
    {
        "player_id": "mookie_betts",
        "player_name": "Mookie Betts",
        "sport": "Baseball",
        "position": "OF",
        "team": "LAD",
        "rookie_year": 2014,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3"],
        "match_tokens": ["mookie betts"],
        "search_query_hint": "Mookie Betts",
    },
    {
        "player_id": "yordan_alvarez",
        "player_name": "Yordan Alvarez",
        "sport": "Baseball",
        "position": "DH",
        "team": "HOU",
        "rookie_year": 2019,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3"],
        "match_tokens": ["yordan alvarez"],
        "search_query_hint": "Yordan Alvarez",
    },
    {
        "player_id": "spencer_strider",
        "player_name": "Spencer Strider",
        "sport": "Baseball",
        "position": "P",
        "team": "ATL",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["spencer strider"],
        "search_query_hint": "Spencer Strider",
    },
    {
        "player_id": "pete_crow_armstrong",
        "player_name": "Pete Crow-Armstrong",
        "sport": "Baseball",
        "position": "OF",
        "team": "CHC",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["pete crow armstrong", "crow-armstrong"],
        "search_query_hint": "Pete Crow-Armstrong",
    },
    {
        "player_id": "jackson_chourio",
        "player_name": "Jackson Chourio",
        "sport": "Baseball",
        "position": "OF",
        "team": "MIL",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["jackson chourio", "chourio"],
        "search_query_hint": "Jackson Chourio rookie",
    },
    {
        "player_id": "dylan_crews",
        "player_name": "Dylan Crews",
        "sport": "Baseball",
        "position": "OF",
        "team": "WSH",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["dylan crews"],
        "search_query_hint": "Dylan Crews rookie",
    },
    {
        "player_id": "james_wood",
        "player_name": "James Wood",
        "sport": "Baseball",
        "position": "OF",
        "team": "WSH",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["james wood"],
        "search_query_hint": "James Wood rookie",
    },
    {
        "player_id": "wyatt_langford",
        "player_name": "Wyatt Langford",
        "sport": "Baseball",
        "position": "OF",
        "team": "TEX",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["wyatt langford"],
        "search_query_hint": "Wyatt Langford rookie",
    },
    {
        "player_id": "coby_mayo",
        "player_name": "Coby Mayo",
        "sport": "Baseball",
        "position": "3B",
        "team": "BAL",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["coby mayo"],
        "search_query_hint": "Coby Mayo rookie",
    },
    {
        "player_id": "evan_carter",
        "player_name": "Evan Carter",
        "sport": "Baseball",
        "position": "OF",
        "team": "TEX",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["evan carter"],
        "search_query_hint": "Evan Carter",
    },
    {
        "player_id": "junior_caminero",
        "player_name": "Junior Caminero",
        "sport": "Baseball",
        "position": "3B",
        "team": "TB",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["junior caminero"],
        "search_query_hint": "Junior Caminero rookie",
    },
    {
        "player_id": "kyle_harrison",
        "player_name": "Kyle Harrison",
        "sport": "Baseball",
        "position": "P",
        "team": "SF",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["kyle harrison"],
        "search_query_hint": "Kyle Harrison",
    },
    {
        "player_id": "roki_sasaki",
        "player_name": "Roki Sasaki",
        "sport": "Baseball",
        "position": "P",
        "team": "LAD",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["mlb_star", "whatnot_t3", "rookie_2025"],
        "match_tokens": ["roki sasaki", "sasaki"],
        "search_query_hint": "Roki Sasaki rookie",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# NBA — 25 players
# ─────────────────────────────────────────────────────────────────────────────
_NBA_PLAYERS = [
    {
        "player_id": "victor_wembanyama",
        "player_name": "Victor Wembanyama",
        "sport": "Basketball",
        "position": "C",
        "team": "SAS",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nba_star", "whatnot_t1", "rookie_2023"],
        "match_tokens": ["wembanyama", "wemby"],
        "search_query_hint": "Victor Wembanyama rookie",
    },
    {
        "player_id": "stephen_curry",
        "player_name": "Stephen Curry",
        "sport": "Basketball",
        "position": "PG",
        "team": "GSW",
        "rookie_year": 2010,
        "whatnot_tier": 1,
        "category_tags": ["nba_star", "whatnot_t1"],
        "match_tokens": ["stephen curry", "steph curry"],
        "search_query_hint": "Stephen Curry",
    },
    {
        "player_id": "lebron_james",
        "player_name": "LeBron James",
        "sport": "Basketball",
        "position": "SF",
        "team": "LAL",
        "rookie_year": 2004,
        "whatnot_tier": 1,
        "category_tags": ["nba_star", "whatnot_t1"],
        "match_tokens": ["lebron james", "lebron"],
        "search_query_hint": "LeBron James",
    },
    {
        "player_id": "stephon_castle",
        "player_name": "Stephon Castle",
        "sport": "Basketball",
        "position": "PG",
        "team": "SAS",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["stephon castle"],
        "search_query_hint": "Stephon Castle rookie",
    },
    {
        "player_id": "cooper_flagg",
        "player_name": "Cooper Flagg",
        "sport": "Basketball",
        "position": "F",
        "team": "DAL",
        "rookie_year": 2025,
        "whatnot_tier": 1,
        "category_tags": ["nba_star", "whatnot_t1", "rookie_2025"],
        "match_tokens": ["cooper flagg", "flagg"],
        "search_query_hint": "Cooper Flagg rookie",
    },
    {
        "player_id": "kon_knueppel",
        "player_name": "Kon Knueppel",
        "sport": "Basketball",
        "position": "G",
        "team": "CHA",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["nba_star", "whatnot_t2", "rookie_2025"],
        "match_tokens": ["kon knueppel", "knueppel"],
        "search_query_hint": "Kon Knueppel rookie",
    },
    {
        "player_id": "anthony_edwards",
        "player_name": "Anthony Edwards",
        "sport": "Basketball",
        "position": "SG",
        "team": "MIN",
        "rookie_year": 2021,
        "whatnot_tier": 2,
        "category_tags": ["nba_star", "whatnot_t2"],
        "match_tokens": ["anthony edwards", "ant edwards"],
        "search_query_hint": "Anthony Edwards",
    },
    {
        "player_id": "luka_doncic",
        "player_name": "Luka Doncic",
        "sport": "Basketball",
        "position": "PG",
        "team": "LAL",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["nba_star", "whatnot_t2"],
        "match_tokens": ["luka doncic", "luka"],
        "search_query_hint": "Luka Doncic",
    },
    {
        "player_id": "jayson_tatum",
        "player_name": "Jayson Tatum",
        "sport": "Basketball",
        "position": "SF",
        "team": "BOS",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["nba_star", "whatnot_t2"],
        "match_tokens": ["jayson tatum"],
        "search_query_hint": "Jayson Tatum",
    },
    {
        "player_id": "paolo_banchero",
        "player_name": "Paolo Banchero",
        "sport": "Basketball",
        "position": "F",
        "team": "ORL",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["paolo banchero", "banchero"],
        "search_query_hint": "Paolo Banchero",
    },
    {
        "player_id": "chet_holmgren",
        "player_name": "Chet Holmgren",
        "sport": "Basketball",
        "position": "C",
        "team": "OKC",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["chet holmgren"],
        "search_query_hint": "Chet Holmgren",
    },
    {
        "player_id": "scottie_barnes",
        "player_name": "Scottie Barnes",
        "sport": "Basketball",
        "position": "SF",
        "team": "TOR",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["scottie barnes"],
        "search_query_hint": "Scottie Barnes",
    },
    {
        "player_id": "tyrese_haliburton",
        "player_name": "Tyrese Haliburton",
        "sport": "Basketball",
        "position": "PG",
        "team": "IND",
        "rookie_year": 2021,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3"],
        "match_tokens": ["tyrese haliburton"],
        "search_query_hint": "Tyrese Haliburton",
    },
    {
        "player_id": "tyrese_maxey",
        "player_name": "Tyrese Maxey",
        "sport": "Basketball",
        "position": "PG",
        "team": "PHI",
        "rookie_year": 2021,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3"],
        "match_tokens": ["tyrese maxey"],
        "search_query_hint": "Tyrese Maxey",
    },
    {
        "player_id": "franz_wagner",
        "player_name": "Franz Wagner",
        "sport": "Basketball",
        "position": "SF",
        "team": "ORL",
        "rookie_year": 2022,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["franz wagner"],
        "search_query_hint": "Franz Wagner",
    },
    {
        "player_id": "keyonte_george",
        "player_name": "Keyonte George",
        "sport": "Basketball",
        "position": "PG",
        "team": "UTA",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["keyonte george"],
        "search_query_hint": "Keyonte George rookie",
    },
    {
        "player_id": "jalen_duren",
        "player_name": "Jalen Duren",
        "sport": "Basketball",
        "position": "C",
        "team": "DET",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["jalen duren"],
        "search_query_hint": "Jalen Duren",
    },
    {
        "player_id": "jabari_smith_jr",
        "player_name": "Jabari Smith Jr.",
        "sport": "Basketball",
        "position": "PF",
        "team": "HOU",
        "rookie_year": 2023,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2022"],
        "match_tokens": ["jabari smith", "jabari smith jr"],
        "search_query_hint": "Jabari Smith Jr",
    },
    {
        "player_id": "ausar_thompson",
        "player_name": "Ausar Thompson",
        "sport": "Basketball",
        "position": "SF",
        "team": "DET",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["ausar thompson"],
        "search_query_hint": "Ausar Thompson rookie",
    },
    {
        "player_id": "amen_thompson",
        "player_name": "Amen Thompson",
        "sport": "Basketball",
        "position": "SF",
        "team": "HOU",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["amen thompson"],
        "search_query_hint": "Amen Thompson rookie",
    },
    {
        "player_id": "jaime_jaquez_jr",
        "player_name": "Jaime Jaquez Jr.",
        "sport": "Basketball",
        "position": "SF",
        "team": "MIA",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["jaime jaquez", "jaquez jr"],
        "search_query_hint": "Jaime Jaquez Jr",
    },
    {
        "player_id": "derrick_whitehead",
        "player_name": "Derrick Whitehead",
        "sport": "Basketball",
        "position": "SG",
        "team": "NYK",
        "rookie_year": 2024,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2023"],
        "match_tokens": ["derrick whitehead"],
        "search_query_hint": "Derrick Whitehead rookie",
    },
    {
        "player_id": "isaiah_collier",
        "player_name": "Isaiah Collier",
        "sport": "Basketball",
        "position": "PG",
        "team": "UTA",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["isaiah collier"],
        "search_query_hint": "Isaiah Collier rookie",
    },
    {
        "player_id": "dalton_knecht",
        "player_name": "Dalton Knecht",
        "sport": "Basketball",
        "position": "SG",
        "team": "LAL",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["dalton knecht"],
        "search_query_hint": "Dalton Knecht rookie",
    },
    {
        "player_id": "tristan_da_silva",
        "player_name": "Tristan da Silva",
        "sport": "Basketball",
        "position": "SF",
        "team": "ORL",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba_star", "whatnot_t3", "rookie_2024"],
        "match_tokens": ["tristan da silva"],
        "search_query_hint": "Tristan da Silva rookie",
    },
    # ── NBA sync from _PLAYER_MASTER 2026-06-29 (fixes NBA target throttle) ──
    {
        "player_id": "michael_jordan",
        "player_name": "Michael Jordan",
        "sport": "Basketball",
        "rookie_year": 1986,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["michael jordan", "jordan"],
        "search_query_hint": "Michael Jordan",
    },
    {
        "player_id": "kobe_bryant",
        "player_name": "Kobe Bryant",
        "sport": "Basketball",
        "rookie_year": 1996,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["kobe bryant", "bryant"],
        "search_query_hint": "Kobe Bryant",
    },
    {
        "player_id": "caitlin_clark",
        "player_name": "Caitlin Clark",
        "sport": "Basketball",
        "rookie_year": 2024,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["caitlin clark", "clark"],
        "search_query_hint": "Caitlin Clark",
    },
    {
        "player_id": "nikola_jokic",
        "player_name": "Nikola Jokic",
        "sport": "Basketball",
        "rookie_year": 2015,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["nikola jokic", "jokic"],
        "search_query_hint": "Nikola Jokic",
    },
    {
        "player_id": "devin_booker",
        "player_name": "Devin Booker",
        "sport": "Basketball",
        "rookie_year": 2015,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["devin booker", "booker"],
        "search_query_hint": "Devin Booker",
    },
    {
        "player_id": "damian_lillard",
        "player_name": "Damian Lillard",
        "sport": "Basketball",
        "rookie_year": 2012,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["damian lillard", "lillard"],
        "search_query_hint": "Damian Lillard",
    },
    {
        "player_id": "giannis_antetokounmpo",
        "player_name": "Giannis Antetokounmpo",
        "sport": "Basketball",
        "rookie_year": 2013,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["giannis antetokounmpo", "antetokounmpo"],
        "search_query_hint": "Giannis Antetokounmpo",
    },
    {
        "player_id": "a_ja_wilson",
        "player_name": "A'ja Wilson",
        "sport": "Basketball",
        "rookie_year": 2018,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["a'ja wilson", "wilson"],
        "search_query_hint": "A'ja Wilson",
    },
    {
        "player_id": "paige_bueckers",
        "player_name": "Paige Bueckers",
        "sport": "Basketball",
        "rookie_year": 2025,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["paige bueckers", "bueckers"],
        "search_query_hint": "Paige Bueckers",
    },
    {
        "player_id": "shai_gilgeous_alexander",
        "player_name": "Shai Gilgeous-Alexander",
        "sport": "Basketball",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["shai gilgeous-alexander", "gilgeous-alexander"],
        "search_query_hint": "Shai Gilgeous-Alexander",
    },
    {
        "player_id": "jalen_brunson",
        "player_name": "Jalen Brunson",
        "sport": "Basketball",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["jalen brunson", "brunson"],
        "search_query_hint": "Jalen Brunson",
    },
    {
        "player_id": "trae_young",
        "player_name": "Trae Young",
        "sport": "Basketball",
        "rookie_year": 2018,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["trae young", "young"],
        "search_query_hint": "Trae Young",
    },
    {
        "player_id": "ja_morant",
        "player_name": "Ja Morant",
        "sport": "Basketball",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["ja morant", "morant"],
        "search_query_hint": "Ja Morant",
    },
    {
        "player_id": "zion_williamson",
        "player_name": "Zion Williamson",
        "sport": "Basketball",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["zion williamson", "williamson"],
        "search_query_hint": "Zion Williamson",
    },
    {
        "player_id": "scoot_henderson",
        "player_name": "Scoot Henderson",
        "sport": "Basketball",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["scoot henderson", "henderson"],
        "search_query_hint": "Scoot Henderson",
    },
    {
        "player_id": "breanna_stewart",
        "player_name": "Breanna Stewart",
        "sport": "Basketball",
        "rookie_year": 2016,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["breanna stewart", "stewart"],
        "search_query_hint": "Breanna Stewart",
    },
    {
        "player_id": "napheesa_collier",
        "player_name": "Napheesa Collier",
        "sport": "Basketball",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["napheesa collier", "collier"],
        "search_query_hint": "Napheesa Collier",
    },
    {
        "player_id": "sabrina_ionescu",
        "player_name": "Sabrina Ionescu",
        "sport": "Basketball",
        "rookie_year": 2020,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["sabrina ionescu", "ionescu"],
        "search_query_hint": "Sabrina Ionescu",
    },
    {
        "player_id": "dylan_harper",
        "player_name": "Dylan Harper",
        "sport": "Basketball",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba", "whatnot_t3"],
        "match_tokens": ["dylan harper", "harper"],
        "search_query_hint": "Dylan Harper",
    },
    {
        "player_id": "vj_edgecombe",
        "player_name": "VJ Edgecombe",
        "sport": "Basketball",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba", "whatnot_t3"],
        "match_tokens": ["vj edgecombe", "edgecombe"],
        "search_query_hint": "VJ Edgecombe",
    },
    {
        "player_id": "khaman_maluach",
        "player_name": "Khaman Maluach",
        "sport": "Basketball",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["nba", "whatnot_t3"],
        "match_tokens": ["khaman maluach", "maluach"],
        "search_query_hint": "Khaman Maluach",
    },
    {
        "player_id": "kevin_durant",
        "player_name": "Kevin Durant",
        "sport": "Basketball",
        "rookie_year": 2007,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["kevin durant", "durant"],
        "search_query_hint": "Kevin Durant",
    },
    {
        "player_id": "magic_johnson",
        "player_name": "Magic Johnson",
        "sport": "Basketball",
        "rookie_year": 1980,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["magic johnson", "johnson"],
        "search_query_hint": "Magic Johnson",
    },
    {
        "player_id": "larry_bird",
        "player_name": "Larry Bird",
        "sport": "Basketball",
        "rookie_year": 1979,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["larry bird", "bird"],
        "search_query_hint": "Larry Bird",
    },
    {
        "player_id": "shaquille_o_neal",
        "player_name": "Shaquille O'Neal",
        "sport": "Basketball",
        "rookie_year": 1992,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["shaquille o'neal", "o'neal"],
        "search_query_hint": "Shaquille O'Neal",
    },
    {
        "player_id": "allen_iverson",
        "player_name": "Allen Iverson",
        "sport": "Basketball",
        "rookie_year": 1996,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["allen iverson", "iverson"],
        "search_query_hint": "Allen Iverson",
    },
    {
        "player_id": "tim_duncan",
        "player_name": "Tim Duncan",
        "sport": "Basketball",
        "rookie_year": 1997,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["tim duncan", "duncan"],
        "search_query_hint": "Tim Duncan",
    },
    {
        "player_id": "kevin_garnett",
        "player_name": "Kevin Garnett",
        "sport": "Basketball",
        "rookie_year": 1995,
        "whatnot_tier": 1,
        "category_tags": ["nba", "whatnot_t1"],
        "match_tokens": ["kevin garnett", "garnett"],
        "search_query_hint": "Kevin Garnett",
    },
    {
        "player_id": "kyrie_irving",
        "player_name": "Kyrie Irving",
        "sport": "Basketball",
        "rookie_year": 2011,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["kyrie irving", "irving"],
        "search_query_hint": "Kyrie Irving",
    },
    {
        "player_id": "jaylen_brown",
        "player_name": "Jaylen Brown",
        "sport": "Basketball",
        "rookie_year": 2016,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["jaylen brown", "brown"],
        "search_query_hint": "Jaylen Brown",
    },
    {
        "player_id": "bam_adebayo",
        "player_name": "Bam Adebayo",
        "sport": "Basketball",
        "rookie_year": 2017,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["bam adebayo", "adebayo"],
        "search_query_hint": "Bam Adebayo",
    },
    {
        "player_id": "kawhi_leonard",
        "player_name": "Kawhi Leonard",
        "sport": "Basketball",
        "rookie_year": 2011,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["kawhi leonard", "leonard"],
        "search_query_hint": "Kawhi Leonard",
    },
    {
        "player_id": "jimmy_butler",
        "player_name": "Jimmy Butler",
        "sport": "Basketball",
        "rookie_year": 2011,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["jimmy butler", "butler"],
        "search_query_hint": "Jimmy Butler",
    },
    {
        "player_id": "de_aaron_fox",
        "player_name": "De'Aaron Fox",
        "sport": "Basketball",
        "rookie_year": 2017,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["de'aaron fox", "fox"],
        "search_query_hint": "De'Aaron Fox",
    },
    {
        "player_id": "donovan_mitchell",
        "player_name": "Donovan Mitchell",
        "sport": "Basketball",
        "rookie_year": 2017,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["donovan mitchell", "mitchell"],
        "search_query_hint": "Donovan Mitchell",
    },
    {
        "player_id": "paul_george",
        "player_name": "Paul George",
        "sport": "Basketball",
        "rookie_year": 2010,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["paul george", "george"],
        "search_query_hint": "Paul George",
    },
    {
        "player_id": "domantas_sabonis",
        "player_name": "Domantas Sabonis",
        "sport": "Basketball",
        "rookie_year": 2016,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["domantas sabonis", "sabonis"],
        "search_query_hint": "Domantas Sabonis",
    },
    {
        "player_id": "alperen_sengun",
        "player_name": "Alperen Sengun",
        "sport": "Basketball",
        "rookie_year": 2021,
        "whatnot_tier": 2,
        "category_tags": ["nba", "whatnot_t2"],
        "match_tokens": ["alperen sengun", "sengun"],
        "search_query_hint": "Alperen Sengun",
    },
]

# Combined seed — 102 players (52 NFL + 25 MLB + 25 NBA)
_EXTRA_SEED_PLAYERS = [
    {
        "player_id": "tom_brady",
        "player_name": "Tom Brady",
        "sport": "Football",
        "rookie_year": 2000,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["tom brady", "brady"],
        "search_query_hint": "Tom Brady",
    },
    {
        "player_id": "aaron_judge",
        "player_name": "Aaron Judge",
        "sport": "Baseball",
        "rookie_year": 2017,
        "whatnot_tier": 1,
        "category_tags": ["baseball", "whatnot_t1"],
        "match_tokens": ["aaron judge", "judge"],
        "search_query_hint": "Aaron Judge",
    },
    {
        "player_id": "mike_trout",
        "player_name": "Mike Trout",
        "sport": "Baseball",
        "rookie_year": 2011,
        "whatnot_tier": 1,
        "category_tags": ["baseball", "whatnot_t1"],
        "match_tokens": ["mike trout", "trout"],
        "search_query_hint": "Mike Trout",
    },
    {
        "player_id": "bryce_harper",
        "player_name": "Bryce Harper",
        "sport": "Baseball",
        "rookie_year": 2012,
        "whatnot_tier": 1,
        "category_tags": ["baseball", "whatnot_t1"],
        "match_tokens": ["bryce harper", "harper"],
        "search_query_hint": "Bryce Harper",
    },
    {
        "player_id": "jaxson_dart",
        "player_name": "Jaxson Dart",
        "sport": "Football",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["jaxson dart", "dart"],
        "search_query_hint": "Jaxson Dart",
    },
    {
        "player_id": "luther_burden_iii",
        "player_name": "Luther Burden III",
        "sport": "Football",
        "rookie_year": 2024,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["luther burden iii", "iii"],
        "search_query_hint": "Luther Burden III",
    },
    {
        "player_id": "tetairoa_mcmillan",
        "player_name": "Tetairoa McMillan",
        "sport": "Football",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["tetairoa mcmillan", "mcmillan"],
        "search_query_hint": "Tetairoa McMillan",
    },
    {
        "player_id": "treveyon_henderson",
        "player_name": "TreVeyon Henderson",
        "sport": "Football",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["treveyon henderson", "henderson"],
        "search_query_hint": "TreVeyon Henderson",
    },
    {
        "player_id": "jahmyr_gibbs",
        "player_name": "Jahmyr Gibbs",
        "sport": "Football",
        "rookie_year": 2023,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["jahmyr gibbs", "gibbs"],
        "search_query_hint": "Jahmyr Gibbs",
    },
    {
        "player_id": "vladimir_guerrero_jr",
        "player_name": "Vladimir Guerrero Jr.",
        "sport": "Baseball",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["baseball", "whatnot_t2"],
        "match_tokens": ["vladimir guerrero jr.", "jr."],
        "search_query_hint": "Vladimir Guerrero Jr.",
    },
    {
        "player_id": "roman_anthony",
        "player_name": "Roman Anthony",
        "sport": "Baseball",
        "rookie_year": 2025,
        "whatnot_tier": 2,
        "category_tags": ["baseball", "whatnot_t2"],
        "match_tokens": ["roman anthony", "anthony"],
        "search_query_hint": "Roman Anthony",
    },
    {
        "player_id": "jeremiyah_love",
        "player_name": "Jeremiyah Love",
        "sport": "Football",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["football", "whatnot_t3"],
        "match_tokens": ["jeremiyah love", "love"],
        "search_query_hint": "Jeremiyah Love",
    },
    {
        "player_id": "david_bailey",
        "player_name": "David Bailey",
        "sport": "Football",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["football", "whatnot_t3"],
        "match_tokens": ["david bailey", "bailey"],
        "search_query_hint": "David Bailey",
    },
    {
        "player_id": "carnell_tate",
        "player_name": "Carnell Tate",
        "sport": "Football",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["football", "whatnot_t3"],
        "match_tokens": ["carnell tate", "tate"],
        "search_query_hint": "Carnell Tate",
    },
    {
        "player_id": "fernando_mendoza",
        "player_name": "Fernando Mendoza",
        "sport": "Football",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["football", "whatnot_t3"],
        "match_tokens": ["fernando mendoza", "mendoza"],
        "search_query_hint": "Fernando Mendoza",
    },
    {
        "player_id": "jac_caglianone",
        "player_name": "Jac Caglianone",
        "sport": "Baseball",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["baseball", "whatnot_t3"],
        "match_tokens": ["jac caglianone", "caglianone"],
        "search_query_hint": "Jac Caglianone",
    },
    {
        "player_id": "colson_montgomery",
        "player_name": "Colson Montgomery",
        "sport": "Baseball",
        "rookie_year": 2025,
        "whatnot_tier": 3,
        "category_tags": ["baseball", "whatnot_t3"],
        "match_tokens": ["colson montgomery", "montgomery"],
        "search_query_hint": "Colson Montgomery",
    },
    {
        "player_id": "jacob_misiorowski",
        "player_name": "Jacob Misiorowski",
        "sport": "Baseball",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["baseball", "whatnot_t3"],
        "match_tokens": ["jacob misiorowski", "misiorowski"],
        "search_query_hint": "Jacob Misiorowski",
    },
    {
        "player_id": "samuel_basallo",
        "player_name": "Samuel Basallo",
        "sport": "Baseball",
        "rookie_year": 2026,
        "whatnot_tier": 3,
        "category_tags": ["baseball", "whatnot_t3"],
        "match_tokens": ["samuel basallo", "basallo"],
        "search_query_hint": "Samuel Basallo",
    },
    {
        "player_id": "ethan_holliday",
        "player_name": "Ethan Holliday",
        "sport": "Baseball",
        "rookie_year": 2027,
        "whatnot_tier": 3,
        "category_tags": ["baseball", "whatnot_t3"],
        "match_tokens": ["ethan holliday", "holliday"],
        "search_query_hint": "Ethan Holliday",
    },
    {
        "player_id": "fernando_tatis_jr",
        "player_name": "Fernando Tatis Jr.",
        "sport": "Baseball",
        "rookie_year": 2019,
        "whatnot_tier": 1,
        "category_tags": ["baseball", "whatnot_t1"],
        "match_tokens": ["fernando tatis jr.", "jr."],
        "search_query_hint": "Fernando Tatis Jr.",
    },
    {
        "player_id": "a_j_brown",
        "player_name": "A.J. Brown",
        "sport": "Football",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["a.j. brown", "brown"],
        "search_query_hint": "A.J. Brown",
    },
    {
        "player_id": "nico_collins",
        "player_name": "Nico Collins",
        "sport": "Football",
        "rookie_year": 2021,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["nico collins", "collins"],
        "search_query_hint": "Nico Collins",
    },
    {
        "player_id": "brock_purdy",
        "player_name": "Brock Purdy",
        "sport": "Football",
        "rookie_year": 2022,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["brock purdy", "purdy"],
        "search_query_hint": "Brock Purdy",
    },
    {
        "player_id": "matthew_stafford",
        "player_name": "Matthew Stafford",
        "sport": "Football",
        "rookie_year": 2009,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["matthew stafford", "stafford"],
        "search_query_hint": "Matthew Stafford",
    },
    {
        "player_id": "dk_metcalf",
        "player_name": "DK Metcalf",
        "sport": "Football",
        "rookie_year": 2019,
        "whatnot_tier": 2,
        "category_tags": ["football", "whatnot_t2"],
        "match_tokens": ["dk metcalf", "metcalf"],
        "search_query_hint": "DK Metcalf",
    },
    {
        "player_id": "jerry_rice",
        "player_name": "Jerry Rice",
        "sport": "Football",
        "rookie_year": 1985,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["jerry rice", "rice"],
        "search_query_hint": "Jerry Rice",
    },
    {
        "player_id": "barry_sanders",
        "player_name": "Barry Sanders",
        "sport": "Football",
        "rookie_year": 1989,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["barry sanders", "sanders"],
        "search_query_hint": "Barry Sanders",
    },
    {
        "player_id": "joe_montana",
        "player_name": "Joe Montana",
        "sport": "Football",
        "rookie_year": 1979,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["joe montana", "montana"],
        "search_query_hint": "Joe Montana",
    },
    {
        "player_id": "walter_payton",
        "player_name": "Walter Payton",
        "sport": "Football",
        "rookie_year": 1975,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["walter payton", "payton"],
        "search_query_hint": "Walter Payton",
    },
    {
        "player_id": "randy_moss",
        "player_name": "Randy Moss",
        "sport": "Football",
        "rookie_year": 1998,
        "whatnot_tier": 1,
        "category_tags": ["football", "whatnot_t1"],
        "match_tokens": ["randy moss", "moss"],
        "search_query_hint": "Randy Moss",
    },
]

SEED_PLAYERS = _NFL_PLAYERS + _MLB_PLAYERS + _NBA_PLAYERS + _EXTRA_SEED_PLAYERS

# Whatnot velocity lookups
WHATNOT_TIER_BY_PLAYER_ID: dict = {
    p["player_id"]: p["whatnot_tier"] for p in SEED_PLAYERS
}

WHATNOT_TIER_LABELS = {
    1: "T1 INSTANT",
    2: "T2 FAST",
    3: "T3 STEADY",
}

WHATNOT_TIER_COLORS = {
    1: "#22c55e",
    2: "#f59e0b",
    3: "#94a3b8",
}


def players_by_id():
    base = {p["player_id"]: dict(p) for p in SEED_PLAYERS}
    try:
        from player_universe import extend_seed_map_with_universe
        extend_seed_map_with_universe(base)
    except Exception:
        pass
    return base
